apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omsorgspenger-tilgangsstyring
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  accessPolicy:
    inbound:
      rules:
        - application: omsorgspenger-sak
        - application: omsorgspenger-rammemeldinger
        - application: omsorgsdager
        - application: k9-aarskvantum
          namespace: default
          cluster: {{clusterFss}}
    outbound:
      external:
      {{#each externalHosts as |host|}}
         - host: {{host}}
      {{/each}}
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
